const fs = require('fs')
let script = fs.readFileSync("./script.js",{encoding:"utf-8"})
console.log(script)
script.replace("GOOGLE_SERVICE_ACCOUNT_EMAIL", process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL)
script.replace("GOOGLE_PRIVATE_KEY", process.env.GOOGLE_PRIVATE_KEY)
fs.writeFileSync('./script.js', script)